### PR TITLE
Add /tor endpoints to support tor-proxied service calls

### PR DESCRIPTION
**Pull request by user411**
Add tor support to the proxy server and /tor prefixed endpoints for choosing to use. Added loading indicators and config selection for tor.

Screen Shot 2021-09-29 at 1 25 24 PM

Individual announcement loading looks like last item here:
Screen Shot 2021-09-29 at 1 26 52 PM

### CODE REVIEW

**Comment by Christewart** [comment]
So this is what i see when i attempt to run this

Screenshot from 2021-09-30 15-18-00

I'm running tor

Screenshot from 2021-09-30 15-18-45

**Comment by Christewart** [comment]
Happy path works :100: for me

I tried to test the sad path by posting an announcement after shutting down my tor binary, but I still have the tor checkbox checked on my UI and it silently fails and produces these logs on the backend. Perhaps we want some sort of UI pop up that says "tor not connected" or something like that? This is on 5aaf9215ebc30223020a50111af0dd202a465575

Screenshot from 2021-09-30 15-32-59

**Comment by user411** [comment]
Handles no-tor more gracefully now. Logs error on the backend, passes specific tor connection error message to frontend. If we want to do something in general with them, we could count them and act on them somehow. Get’s error dialogs bubbled up to show failures for now.

**Comment by user411** [comment]
Fixes #17

**Review by Christewart — APPROVED** [review]
So the first time i fired up this UI on  ceb75025bdff0b95a6c1ca0591f98e5df76b280f

Screenshot from 2021-10-01 13-54-12

I think this is the same errors we are receiving from the oracle explorer? 

I refreshed the browser and this went away. 

I tested both posting announcements and attestations with tor and this worked fine, this is what i posted to the explorer: 

https://test.oracle.suredbits.com/announcement/47b6504127b133f64b40b9feb228b85914b8d33cd6f680deb2365e682070b48e

Next i shutdown my tor and then tried to announce something and got this nice error message

Screenshot from 2021-10-01 13-55-56

**Comment by user411** [comment]
Tor is unpredictable, so any given web call may fail under you. As to the why on the 40X errors, the prod server seems to be better defended than the test server and I have seen less 40X type behavior there.

**Pull request merged**
