### PR TITLE
Add header, Setup routes, Styling updates

### PR DESCRIPTION
**Pull request by user411**
Adds header, puts pages on routes, contract details update

Screen Shot 2021-12-13 at 3 52 14 PM
Screen Shot 2021-12-13 at 3 52 34 PM

### CODE REVIEW

**Comment by user411** [comment]
newOffer
acceptOffer
contractDetail

**Comment by Christewart** [comment]
I think `DLC returns` should be moved to the `Contracts` tab. 

Screenshot from 2021-12-20 08-57-21

Also IMO it would be nice to go directly to the contract tabs if you have DLCs in your wallet.

What do you think about moving the `Balance` into the header here? I think we would only display `Total Balance` on the header. This gives me an idea of how much money I have while looking at the contracts tab to create a DLC, especially when we have htis nice little wallet icon here

Screenshot from 2021-12-20 08-59-25
Screenshot from 2021-12-20 08-59-10

**Comment by user411** [comment]
Screen Shot 2021-12-20 at 1 55 36 PM
Screen Shot 2021-12-20 at 1 56 23 PM

**Comment by Christewart** [comment]
This LGTM, are we good for merge on this PR?

**Comment by user411** [comment]
Yes

**Review by Christewart — APPROVED** [review]

**Pull request merged**
