### PR TITLE
Move to Material Design and Reactive Forms

### PR DESCRIPTION
**Pull request by user411**
This moves the Angular forms to Material Design and Reactive Forms.

Lots of small updates, DLCs can be built from Offer or Accepted (via Tor or files). Extended DLC file operations are hidden in this release.

This currently over-validates the New Offer forms when editing collateral and payout amounts. It would ideally not validate when some fields haven't been touched yet.

Screen Shot 2021-12-01 at 1 24 44 PM
Screen Shot 2021-12-01 at 1 25 05 PM
Screen Shot 2021-12-01 at 1 25 14 PM
Screen Shot 2021-12-01 at 1 25 45 PM
Screen Shot 2021-12-01 at 1 25 52 PM

### CODE REVIEW

**Comment by Christewart** [comment]
I think it would be better to bump the refund date by 1 week by default so if the oracle doesn't attest right away the refund tx doesn't become valid

Screenshot from 2021-12-02 08-07-20

**Comment by Christewart** [comment]
It would be nice to have a pre-filled value for the possible range of collateral in the `Your Collateral` field. The contract I am using for this code review is https://oracle.suredbits.com/contract/enum/bf36b3825011b2d1eedf7f7649fa98c20889b5c187e373f7b103c3c7950edbb5 which has a maximum value of 100k sats

**Comment by Christewart** [comment]
I like how you have the the information icon next to other fields, i think we should add it to the `Create Offer` result too saying something like 

>You need to send this hex encoded offer to your counterparty along with your tor address [fill in tor address here]. Your counterparty will accept the offer if they find the terms of the offer agreeable. If they accept your offer, your wallets will build a bitcoin transaction representing the [eventId] bet.

Screenshot from 2021-12-02 08-23-40

**Comment by Christewart** [comment]
It might be nice to link the oracle on the oracle explorer, I think this could be done with this API endpoint on the explorer https://gist.github.com/Christewart/a9e55d9ba582ac9a5ceffa96db9d7e1f#getting-an-oracles-username

If the oracle does not exist on the oracle explorer, i think it is ok to display the public key hex like you do now

Screen Shot 2021-12-02 at 8 54 44 AM

**Comment by Christewart** [comment]
nit: It would be nice to have commas separating numbers especially with sats as they tend to be larger numbers

Screen Shot 2021-12-02 at 9 02 38 AM

**Comment by Christewart** [comment]
The `MAX` button isn't working for me on this page, nothing gets filled in

Screenshot from 2021-12-02 10-59-47

**Comment by Christewart** [comment]
So i'm running into an issue with accepting an offer via Tor. It doesn't seem like the tor negotiation is working for me on d88a8f556fa648facfdbc26f7c288aa432379e2e

When i paste in my offer, and then my peers tor address, i get a dialog popping up to save the file rather than just doing the negotiation behind the scenes

Screen Shot 2021-12-03 at 7 47 29 AM
Screen Shot 2021-12-03 at 7 48 20 AM

**Comment by user411** [comment]
Tor Accept Offer should be working again with the latest commit.

**Comment by Christewart** [comment]
So things worked for me on 129afd62c4983bebe65ed71df34a250d0ac96b6d 

One thing that didn't quite work is updating the DLC table view from `status=Accepted` -> `status=Broadcasted`. IIRC you said there isn't any polling implemented on the UI currently. Is that still the case? If so (and its a known limitation), i'm cool with merging this

Screen Shot 2021-12-03 at 10 11 08 AM
Screen Shot 2021-12-03 at 10 11 26 AM

**Comment by user411** [comment]
There is no state polling on the UI yet.

**Review by Christewart — APPROVED** [review]

**Pull request merged**
