### PR TITLE
Send Funds dialog to Material Design

### PR DESCRIPTION
**Pull request by user411**
Moves the Send Funds dialog to Material Design forms. Supports MAX button to send all available funds in wallet.

Adds ConfirmationDialog after Rebroadcast and Refund operations. Adds link support to ConfirmationDialog.

Screen Shot 2021-12-03 at 1 46 35 PM

### CODE REVIEW

**Comment by user411** [comment]
Screen Shot 2021-12-03 at 3 40 32 PM
)

**Comment by Christewart** [comment]
I kind of expected my entire balance to be filled in to this textbox rather than `MAX`

Screen Shot 2021-12-03 at 7 15 56 PM

also i think we need to figure out a way to bump the default refund date to 1 week to allow for more time if an oracle is delayed in attesting

Screen Shot 2021-12-03 at 7 20 34 PM

**Comment by user411** [comment]
> I kind of expected my entire balance to be filled in to this textbox rather than `All Funds`

Is there an easy way to know what the proper value is to put in place of 'All Funds' taking the fee rate and actual transaction cost (the actual amount that will be received on the other end after sweeping the wallet)?

**Comment by Christewart** [comment]
2 things with this flow (might not be directly related to this PR, can file an issue if preferred)

1. We should rename this from `Oracle Signatures` -> `Oracle Attestations` to be consistent with the oracle explorer and the spec. This should change on our desktop app too.
2. We should change the color of the button when pasting in the signatures to make it easier to identify that the button is clickable

The functionality worked like a charm though on 6ef7e89 :tada: 

Screenshot from 2021-12-06 10-48-56

**Comment by Christewart** [comment]
> > I kind of expected my entire balance to be filled in to this textbox rather than `All Funds`
> 
> Is there an easy way to know what the proper value is to put in place of 'All Funds' taking the fee rate and actual transaction cost (the actual amount that will be received on the other end after sweeping the wallet)?

I don't think there is. We don't have a good way to calculate the fee associated with the sweep transaction in advance since ecdsa digital signatures vary in size thus varying the fee for the entire sweep transaction.

**Comment by Christewart** [comment]
The refund date fix is working for me now.

**Comment by Christewart** [comment]
> Add some verbage around loading hex
> 
> Screen Shot 2021-12-06 at 10 40 38 AM
> 
> Change to Oracle Attestations and set primary color on the action buttons
> 
> Screen Shot 2021-12-06 at 10 59 04 AM

Is there a reason we don't fill in the background color of the button like the buttons here? That is much more visible to me IMO

Screenshot from 2021-12-06 13-51-43

**Comment by user411** [comment]
Screen Shot 2021-12-07 at 10 59 32 AM

**Review by Christewart — APPROVED** [review]

**Pull request merged**
