### PR TITLE
Add address labeling

### PR DESCRIPTION
**Pull request by user411**
Runs over https://github.com/bitcoin-s/bitcoin-s/pull/4175

Screen Shot 2022-03-09 at 11 45 42 AM

### CODE REVIEW

**Comment by Christewart** [comment]
This seems to slow down my wallet when i attempt to switch to the `Wallet` tab. It takes about 5 seconds for my tab to load. I have > 100 addresses or more in my wallet. This labeling is not involved in this performance regressions (i haven't tested the labeling yet). This does not occur on 4a3689a66f2ee1bc8b1ba98dd6313b3ad9317a80

**Review by Christewart — CHANGES_REQUESTED** [review]
### Performance

I still see a noticeable delay on 9e1f42c79fcf9532d1862d973ade2d9d8d8212c3 . Perhaps we should file an issue to address this in a future PR?

### Labeling

it would be nice to have a confirmation dialog when deleting a label. I can imagine accidentally clicking the `x` button which removes the entire label. This would be unfortunate if this happened at bitcoin 2022 as we no longer know what address we served to a particular user. A dialog like `Are you sure you want to delete the label [label-name]?` would be nice.

**Comment by Christewart** [comment]
> This is as fast as you're going to get for this functionality and building stuff on the DOM for all addresses. It would be possible to hide the label fields and require some kind of UX to "open" them, but I'm opposed to a performance issue being filed on this.

Hmm ok, would it be acceptable to document the issue and say performance can't be improved, so we need to figure out a work around (pagination, "hide labels" etc?).

**Comment by user411** [comment]
Screen Shot 2022-03-10 at 8 40 08 AM

**Comment by user411** [comment]
Screen Shot 2022-03-10 at 9 06 50 AM

**Pull request merged**
