### PR TITLE
Second round wallet-server-ui

### PR DESCRIPTION
**Pull request by user411**
Screen Shot 2021-11-08 at 8 59 47 AM
Screen Shot 2021-11-08 at 9 04 42 AM
Screen Shot 2021-11-08 at 9 06 01 AM
Screen Shot 2021-11-08 at 9 06 29 AM
Screen Shot 2021-11-08 at 9 06 35 AM
Screen Shot 2021-11-08 at 9 06 53 AM
Screen Shot 2021-11-08 at 9 07 03 AM

### CODE REVIEW

**Comment by Christewart** [comment]
CI seems to be failing, not sure if it is our fault or npmjs

Looks like the `%` and `sats` labels are off a bit

Screenshot from 2021-11-09 10-26-33

### Contract dialog

When clicking on a contract in my table, I didn't realize that the contract opens _below_ the table. I had to look around for awhile before I realized that. I think i would personally like it opening to the right like you have on Krystal Bull on umbrel. 

Also the `Cancel Contract` button should be contextual to the status of the DLC. [Here](https://github.com/bitcoin-s/bitcoin-s/blob/fd02d3642eb9dd8fbae308b0c2adf0336af8d599/app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCPaneModel.scala#L270) is what that logic exists currently in our old GUI codebase. 

Also it seems that txids don't show up for me funding txid / closing txid.

Screenshot from 2021-11-09 10-35-21


### Building an offer

I attempted to build a new offer with [this announcement](https://oracle.suredbits.com/announcement/8e787a69142b0c635b560a4564bffa29c86d17a1c093a1565abaaf3603a1bd35). It seems to me the endpoints don't get filled in correctly currently. [0-127] when in reality the range is [0 - $262143] with the oracle linked above

Screenshot from 2021-11-09 10-30-26

**Comment by user411** [comment]
What is the shortest path to know the 'numDigits' on an event from this announcement?
Screen Shot 2021-11-09 at 10 42 38 AM
?

**Comment by Christewart** [comment]
> What is the shortest path to know the 'numDigits' on an event descriptor from this announcement? Screen Shot 2021-11-09 at 10 42 38 AM
> 
> I need to do a `maxValue = base.toBigInt.pow(numDigits.toInt) - 1`, but I don't know numDigits.

You should be able to count the number of nonces. We should really add this in the json return from `OracleRoutes` though. Should this be returned as a json field any time a user creates an oracle announcement?

**Comment by user411** [comment]
Should numDigits be the that event serialization? I can see it in

https://test.oracle.suredbits.com/announcement/b4663b7a3aa43d228f350b74f8bbe30a96c9aaf344f8f7589e713863d419f3a2

**Comment by Christewart** [comment]
> Should numDigits be the that event serialization? I can see it in the JSON serialization on
> 
> https://test.oracle.suredbits.com/announcement/b4663b7a3aa43d228f350b74f8bbe30a96c9aaf344f8f7589e713863d419f3a2

Sadly, i think we have divergent serializers between the oracle explorer and our bitcoin-s codebase. We should definitely unify these at some point, here is what lives on the open source side of things: https://github.com/bitcoin-s/bitcoin-s/blob/5a5f1e00c7b4d48e365ee4fa1e437db0b8eb8f19/app/oracle-server/src/main/scala/org/bitcoins/oracle/server/OracleRoutes.scala#L174

**Comment by user411** [comment]
Np, counting nounces works. Thank you.

**Comment by Christewart** [comment]
> Np, counting nounces works. Thank you.

I'll file an issue on the backend repo so that we can fix this eventually.

**Pull request merged**
