### PR TITLE
Update tool tip on contract/offer dialogs to be 'Send to Contact'

### PR DESCRIPTION
**Pull request by Christewart**
H/T to @benthecarman for finding this one. Previously it would be `Add Contact` which confused him as he didn't want to add a contac, he wanted to send to a contact.

Screenshot from 2022-08-24 14-59-08

### CODE REVIEW

**Comment by user411** [comment]
"Select Contact"?

**Comment by Christewart** [comment]
> "Select Contact"?

Yes, add contact makes users think they are adding a new contact

Screenshot from 2022-08-25 06-13-42

**Comment by user411** [comment]
Same needs to change in contact-detail.component.html and accept-offer.component.html

**Comment by Christewart** [comment]
Done in #185

**Pull request closed without merging**
