### PR TITLE
Wallet UI with Websockets data

### PR DESCRIPTION
**Pull request by user411**
This frontend runs over https://github.com/bitcoin-s/bitcoin-s/pull/3926 

It add websocket support, initial loading indicator, Network page, header rework, Wallet Balance/Network Status hover menus, initial route loading logic (/contracts or /wallet), About page links, removed autocomplete behavior on hex paste fields, moved Cancel/Refund actions to small button next to State on Contract Detail, fixes broken Execute button on DLCs, ...

### CODE REVIEW

**Comment by Christewart** [comment]
What events via the websocket should be shown on the UI ? I created an offer this morning and canceled an offer and i'm not sure if any of the websocket events made it to the UI.

**Comment by user411** [comment]
Here's what I see creating and canceling a contract:

Screen Shot 2021-12-29 at 10 02 22 AM
Screen Shot 2021-12-29 at 10 02 47 AM

Creating gets a `dlcstatechange` event and cancelling does nothing (it is manually removed because there is no event yet).

**Comment by user411** [comment]
Added zip backup functionality to the web UI. You MUST have ~.bitcoin-s/backup/ present for this to work, it does not currently try to create /backup

Screen Shot 2021-12-29 at 12 05 00 PM

**Comment by Christewart** [comment]
I'm using this contract info: https://oracle.suredbits.com/contract/numeric/cde7c0e98f9173c0e0de310f1a5a804193f6fbb583f4c390dccbb857037a368c

When pasting in the contract info, i expected the `total collateral` field here to be filled in, and i would have to fill in my collateral

Screenshot from 2022-01-03 10-25-28

another thing i have a suspicion of is that the UI commit hash is broken, here is what i see

Screenshot from 2022-01-03 10-28-22

129afd6

and i'm running this from `git log`. I also see all the ws updates in the console so i believe i'm running the correct commit.

Screenshot from 2022-01-03 10-29-04

**Comment by user411** [comment]
You have to rebuild the UI to update the commit hash `wallet-server-ui-proxy % npm run build`.

**Comment by user411** [comment]
Total Collateral now sets from Contract Infos.

**Comment by Christewart** [comment]
This button is broken for me, it copies 

>0:0:0:0:0:0:0:0:2862

to my clipboard

Screenshot from 2022-01-03 12-32-20

**Pull request merged**
