### PR TITLE
Wallet server UI 003

### PR DESCRIPTION
**Pull request by user411**
Third edition of wallet UI. Supports acceptdlcoffer via Tor for both contract types. Enables a number of other contract interactions like cancel, execute, rebroadcast funding txs. Add number and date formatting, unit labels, payouts on new offers. Handles ContractInfo hex to instantiate Build Offer, but doesn't execute yet. Adds MAX button to sending funds, but underlying sweep functionality is untested.

Currently cannot execute a DLC and have wallet in good state due to bitcoin-s/bitcoin-s#3826.

Screen Shot 2021-11-16 at 8 47 49 AM

Screen Shot 2021-11-16 at 8 48 41 AM

Screen Shot 2021-11-16 at 8 48 15 AM

### CODE REVIEW

**Comment by user411** [comment]
Screen Shot 2021-11-17 at 1 30 42 PM

**Comment by Christewart** [comment]
I get this error when trying to build `wallet-server-ui` locally

Screenshot from 2021-11-19 08-32-17

**Comment by user411** [comment]
Looks like the default is to start throwing errors for styles at 4kb. Upped it in the config. If you pull latest, should be able to `npm run build`

**Comment by Christewart** [comment]
One thing when doing a DLC is the status doesn't seem to get updated in the table if you are the offerer. The funding tx got broadcast to the blockchain and my DLC was still in 'offered' state. Upon refreshing the browser window this got updated to `Broadcast`. Maybe we don't want to tackle this on this PR, if so i can file an issue to address in the future.

Screenshot from 2021-11-19 11-07-10

The claim flow worked fine for me. I broadcast the CET from my web wallet and it updated perfectly :tada:

**Comment by user411** [comment]
The is no polling whatsoever on the wallet yet to update state.

**Pull request merged**
