### PR TITLE
Basic proxy server

### PR DESCRIPTION
**Pull request by user411**
Current state of proxy server to run oracle-server-ui

### CODE REVIEW

**Comment by user411** [comment]
Added a UI that runs over the proxy server build with Angular material

Screen Shot 2021-09-02 at 5 47 00 PM
Screen Shot 2021-09-02 at 5 49 04 PM
Screen Shot 2021-09-02 at 5 49 22 PM
Screen Shot 2021-09-02 at 5 47 53 PM

**Comment by benthecarman** [comment]
needs dark mode :)

**Comment by Christewart** [comment]
Nice feature at the bottom (maybe movie it to the top?) notifying the user that the oracle server isn't running

**Comment by Christewart** [comment]
We still need to implement THE most important feature :p 

Screen Shot 2021-09-03 at 8 44 01 AM

**Comment by user411** [comment]
<not checked in yet>
Screen Shot 2021-09-03 at 8 59 03 AM

**Review by Christewart — APPROVED** [review]

**Pull request merged**
